print("Hi i am Creator and this is my comix")

print("Hacker:Hi do u want get money?")
print("Hakcer:Oh i forgot i cant see ur text but i think u say yes")
print("Amy:Hi i am amy ur friend and we will work in 1 corpus")
print("You:Hi...?  (desriptions You dont talk with girls) ")
print("Amy:Ok go i will show u all")
print("You:Ok.....?")
print("$#%#%:He in the town?")
print("Hacker:Yes sir")
print("$#%#%:Ok i am coming")
print("You:Hey.... who is hacker?")
print("Amy:is my dad")
print("You:Okkkk.....")
print("$#%#%:This is funny)")
print("Chapter 1 end")
print("Chapter 2 Secrets?")
print("Amy: ok whats ur name?")
print("You:Uhmm my name oh i am silly i forgot my name u can call me jack")
print("Achiwment:Name jack")
print("Amy:Ok jack is funny name")
print("Jack:Thanks amy")
print("Arina:Hey amy where are u")
print("Amy:Oh no dont ask her pls")
print("Jack:Ok...")
print("Arina:Hey man do u see girl amy?")
print("Jack:no...")
print("Arina:Ok")
print("$#%#%:Hey arina do u find him?")
print("Arina:WHAT U BUT..")
print("$#%#%:Yea i am back arina")
print("Arina:No way u back Ale")
print("Chapter 2 end")
print("Chapter 3 New man?")
print("Arina:No way u back Alex")
print("$#%#%:Yes i am Alex")
print("Alex:U and hacker say sit on island and we back i wait and wait but u guys dont BACK")
print("Arina:and? what do u want to do?")
print("Alex: i have an idea *use pistol*")
print("Hacker:STOP")
print("Alex:hahaha")
print("Hakcer:Kill me and dont touch her")
print("Alex:NO i am gonna kill u but first say ur name")
print("Hakcer:my name is...")
print("Amy:hi dad...")
print("Alex:Hacker is ur dad?")
print("Amy:yes...")
print("Alex:YES i am gonna kill her first")
print("Hakcer:NO")
print("Jack:Break Alexs leg")
print("Alex:NAHHHH dumb kid")
print("Jack:AMY RUN!!!")
print("Amy:OK")
print("Jack use pistol")
print("Ahicwment:Alex die..")
print("Jack:WHA I am kill him...?")
print("Hacker:Yes he die")
print("Jack:Hey u write me *do u want get money*")
print("Hacker:yes u are jack?")
print("Jack:yes")
print("Chapter 3 end")